--- !ditz.rubyforge.org,2008-03-06/project 
name: setf-values
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: setf-values
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.1"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2009-07-08 20:22:54.501750 Z
    - bowbow99 <bowbow99@coffee>
    - created
    - initial release.
- !ditz.rubyforge.org,2008-03-06/release 
  name: future
  status: :unreleased
  release_time: 
  log_events: 
  - - 2009-07-08 20:24:00.909750 Z
    - bowbow99 <bowbow99@coffee>
    - created
    - issues not belong to certain release.
